name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get_cli: ^1.8.1
  dcli: ^0.50.2
  lottie: ^3.1.2
  get: ^4.6.1
  get_storage: 2.1.1
  just_audio: 0.9.38
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

